apiVersion: v1
kind: Service
metadata:
  name: {{ template "gogs.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: metrics
    port: 9188
    protocol: TCP
    targetPort: metrics
  selector:
    app: {{ template "gogs.fullname" . }}
